@startuml
'https://plantuml.com/class-diagram


package RDETest 
{
	package Characters.base
	{
		abstract class ACharacter <<Monobehaviour>>
		{
			- services : List<Object>
			- localServiceLocator : ServiceLocator
			- Awake() : void
		}
		
		abstract class ACharacterAnimator <<M,yellow>>
		{
			- animator : Animator
			
			+ PlayAnimation(string)
		}
 
 		abstract class ACharacterMover <<M,yellow>>
 		{
 			- maxMovementSpeed : float
 			- instantAcceleration : float
 			- accelerationCurve : AnimationCurve
 			+ ChangeMovementSpeed(float)
 			# {abstract} Awake() : void
 			# {abstract} Start() : void
 			# {abstract} Move() : void
 			# {abstract} Stop() : void
		}
		
		abstract class A2DCharacterAnimator <<M,yellow>>
		{
			+ PlayDirectionalAnimation(Vector2)
		}
		
		abstract class A2DCharacterMover <<M,yellow>>
		{
			# rigidbody : Rigidbody2D
		}
		ACharacterMover <|- A2DCharacterMover
		ACharacterAnimator <|- A2DCharacterAnimator
	}

	package Characters.PlayerCharacter
	{
		class Player <<M,yellow>>
		{
		
		}

		class PlayerMover <<M,yellow>>
		{
			- movementAction : InputActionReference
			- FixedUpdate()
			- OnMovementCanceled(CallbackContext)
			- OnMovementInputReceived(CallbackContext)
		}
		
		class PlayerAnimator <<M,yellow>>
		{
			
		}
		PlayerMover <|- A2DCharacterMover
		PlayerAnimator <|-- A2DCharacterAnimator
	}
}


@enduml